/*
 * Copyright (C) 2019 Vincent Wiemann <vw@meshwrt.org>
 *
 * SPDX-License-Identifier: GPL-2.0
 */

#ifndef __MINIDHCP_PROTO_H__
#define __MINIDHCP_PROTO_H__

/* Holds a DHCP message */
typedef struct {
	u8_t op;		/* message op code, message type */
	u8_t htype;		/* hardware address type */
	u8_t hlen;		/* hardware address length */
	u8_t hops;		/* incremented by relay agents */
	u8_t xid[4];		/* transaction ID */
	u16_t secs;		/* seconds since address acquisition or renewal */
	u16_t flags;		/* flags */
	u8_t ciaddr[4];		/* client IP address if client wants to reuse IP in request */
	u8_t yiaddr[4];		/* client IP address assigned by the server in reply */
	u8_t siaddr[4];		/* IP address of the next server to use in bootstrap */
	u8_t giaddr[4];		/* relay agent IP address */
	u8_t chaddr[16];	/* client hardware address */
	u8_t sname[64];		/* server hostname */
	u8_t file[128];		/* boot filename */
	u8_t options[312];	/* optional parameters field */
} dhcp_msg_t;

enum dhcp_op_types {
	BOOTREQUEST = 1,
	BOOTREPLY
};

/* Network ports used by the client/server */
enum dhcp_ports {
	BOOTPSERVER = 67,
	BOOTPCLIENT
};

enum dhcp_msg_type {
	DHCP_DISCOVER = 1,	/* A client asks for a DHCP server on the local network */
	DHCP_OFFER,		/* The server offers an IP address */
	DHCP_REQUEST,		/* A client requests an IP address */
	DHCP_DECLINE,		/* The server declines a request */
	DHCP_ACK,		/* The server acknowledges a request */
	DHCP_NAK,
	DHCP_RELEASE,
	DHCP_INFORM
};

enum {
	/* RFC 1497 Vendor Extensions */

/*	DHCP_OPTION_PAD = 0,*/
	DHCP_OPTION_END = 255,

	DHCP_OPTION_SUBNET_MASK = 1,
/*	DHCP_OPTION_TIME_OFFSET = 2,*/
	DHCP_OPTION_ROUTER = 3,
/*	DHCP_OPTION_TIME_SERVER = 4,
	DHCP_OPTION_NAME_SERVER = 5,*/
	DHCP_OPTION_DOMAIN_NAME_SERVER = 6,
/*	DHCP_OPTION_LOG_SERVER = 7,
	DHCP_OPTION_COOKIE_SERVER = 8,
	DHCP_OPTION_LPR_SERVER = 9,
	DHCP_OPTION_IMPRESS_SERVER = 10,
	DHCP_OPTION_RESOURCE_LOCATION_SERVER = 11,
	DHCP_OPTION_HOST_NAME = 12,
	DHCP_OPTION_BOOT_FILE_SIZE = 13,
	DHCP_OPTION_MERIT_DUMP_FILE = 14,*/
	DHCP_OPTION_DOMAIN_NAME = 15,
/*	DHCP_OPTION_SWAP_SERVER = 16,
	DHCP_OPTION_ROOT_PATH = 17,
	DHCP_OPTION_EXTENSIONS_PATH = 18,*/

	/* IP Layer Parameters per Host */

/*	DHCP_OPTION_IP_FORWARDING = 19,
	DHCP_OPTION_NON_LOCAL_SOURCE_ROUTING = 20,
	DHCP_OPTION_POLICY_FILTER = 21,
	DHCP_OPTION_MAXIMUM_DATAGRAM_REASSEMBLY_SIZE = 22,
	DHCP_OPTION_DEFAULT_IP_TIME_TO_LIVE = 23,
	DHCP_OPTION_PATH_MTU_AGING_TIMEOUT = 24,
	DHCP_OPTION_PATH_MTU_PLATEAU_TABLE = 25,*/

	/* IP Layer Parameters per Interface */

/*	DHCP_OPTION_INTERFACE_MTU = 26,
	DHCP_OPTION_ALL_SUBNETS_ARE_LOCAL = 27,
	DHCP_OPTION_BROADCAST_ADDRESS = 28,
	DHCP_OPTION_PERFORM_MASK_DISCOVERY = 29,
	DHCP_OPTION_MASK_SUPPLIER = 30,
	DHCP_OPTION_PERFORM_ROUTER_DISCOVERY = 31,
	DHCP_OPTION_ROUTER_SOLICITATION_ADDRESS = 32,
	DHCP_OPTION_STATIC_ROUTE = 33,*/

	/* Link Layer Parameters per Interface */

/*	DHCP_OPTION_TRAILER_ENCAPSULATION = 34,
	DHCP_OPTION_ARP_CACHE_TIMEOUT = 35,
	DHCP_OPTION_ETHERNET_ENCAPSULATION = 36,*/

	/* TCP Parameters */

/*	DHCP_OPTION_TCP_DEFAULT_TTL = 37,
	DHCP_OPTION_TCP_KEEPALIVE_INTERVAL = 38,
	DHCP_OPTION_TCP_KEEPALIVE_GARBAGE = 39,*/

	/* Application and Service Parameters */

/*	DHCP_OPTION_NETWORK_INFORMATION_SERVICE_DOMAIN = 40,
	DHCP_OPTION_NETWORK_INFORMATION_SERVERS = 41,
	DHCP_OPTION_NETWORK_TIME_PROTOCOL_SERVERS = 42,
	DHCP_OPTION_VENDOR_SPECIFIC_INFORMATION = 43,
	DHCP_OPTION_NETBIOS_OVER_TCP_IP_NAME_SERVER = 44,
	DHCP_OPTION_NETBIOS_OVER_TCP_IP_DATAGRAM_DISTRIBUTION_SERVER = 4,
	DHCP_OPTION_NETBIOS_OVER_TCP_IP_NODE_TYPE = 46,
	DHCP_OPTION_NETBIOS_OVER_TCP_IP_SCOPE = 47,
	DHCP_OPTION_X_WINDOW_SYSTEM_FONT_SERVER = 48,
	DHCP_OPTION_X_WINDOW_SYSTEM_DISPLAY_MANAGER = 49,*/

	/** DHCP Extensions **/

	DHCP_OPTION_REQUESTED_IP_ADDRESS = 50,
	DHCP_OPTION_IP_ADDRESS_LEASE_TIME = 51,
	DHCP_OPTION_OPTION_OVERLOAD = 52,
/*	DHCP_OPTION_TFTP_SERVER_NAME = 66,
	DHCP_OPTION_BOOTFILE_NAME = 67,*/
	DHCP_OPTION_DHCP_MESSAGE_TYPE = 53,
	DHCP_OPTION_SERVER_IDENTIFIER = 54,
	DHCP_OPTION_PARAMETER_REQUEST_LIST = 55,
/*	DHCP_OPTION_MESSAGE = 56,
	DHCP_OPTION_MAXIMUM_DHCP_MESSAGE_SIZE = 57,
	DHCP_OPTION_RENEWAL_T1_TIME_VALUE = 58,
	DHCP_OPTION_REBINDING_T2_TIME_VALUE = 59,
	DHCP_OPTION_VENDOR_CLASS_IDENTIFIER = 60,
	DHCP_OPTION_CLIENT_IDENTIFIER = 61*/

/*	DHCP_OPTION_NETWORK_INFORMATION_SERVICE_PLUS_DOMAIN = 64,
	DHCP_OPTION_NETWORK_INFORMATION_SERVICE_PLUS_SERVERS = 65,
	DHCP_OPTION_MOBILE_IP_HOME_AGENT = 68,
	DHCP_OPTION_SMTP_SERVER = 69,
	DHCP_OPTION_POP3_SERVER = 70,
	DHCP_OPTION_NNTP_SERVER = 71,
	DHCP_OPTION_DEFAULT_WWW_SERVER = 72,
	DHCP_OPTION_DEFAULT_FINGER_SERVER = 73,
	DHCP_OPTION_DEFAULT_IRC_SERVER = 74,
	DHCP_OPTION_STREETTALK_SERVER = 75,
	DHCP_OPTION_STREETTALK_DIRECTORY_ASSISTANCE_SERVER = 76,*/
};

#endif /* __MINIDHCP_PROTO_H__ */
